web:
  build: .
  links:
   - db
  ports:
   - "8000:80"
  volumes:
   - "./../src:/src"

db:
  image: tutum/mysql:5.6
  volumes:
   - ".db:/var/lib/mysql"
  environment:
   MYSQL_PASS: 123456

pma:
  image: dnhsoft/phpmyadmin:4.4.3
  links:
   - db
  ports:
   - "8001:80"
 

